model_name: 'MultiscaleScoreModel'
model_kwargs:
  score_head_kwargs:
    max_time: 1.
    time_emb_mlp: [512, 256, 128]
    ang_mult: 2.5
    lin_mult: 15.  # In centimeters
    edge_time_encoding: True
    query_time_encoding: False
    key_tensor_field_kwargs:
      irreps_output: '64x0e+32x1e+16x2e'
      irreps_sh: '1x0e+1x1e+1x2e'
      num_heads: 4
      fc_neurons: [-1, 128, 64]    # fc_neurons[0] must be equal to time_emb_dim and length_emb_dim
      length_emb_dim: 64          
      r_cluster_multiscale:        # In centimeters
        - 6.                       # Set higher value (like 6.) if unstable.
      n_layers: 1
      irreps_mlp_mid: 3
      cutoff_method: 'edge_attn'
      r_mincut_nonscalar_sh: 0.1    # In centimeters
      # length_enc_max_r: 100.      # In centimeters

  key_kwargs:
    feature_extractor_name: 'ForwardOnlyFeatureExtractor'
    feature_extractor_kwargs:
      irreps_input: '3x0e'
      irreps_output: '64x0e+32x1e+16x2e'
      n_scales: 1
      irreps_emb:           # mutiscale -> list length must match n_scales
        - '64x0e+32x1e+16x2e'
      irreps_edge_attr:     # mutiscale -> list length must match n_scales
        - '1x0e+1x1e+1x2e'
      num_heads:
        - 4
      fc_neurons:           # mutiscale -> list length must match n_scales
        - [64, 32, 32]
      n_layers:             # mutiscale -> list length must match n_scales
        - 7
      pool_ratio:           # Pooling ratio. For example, p=0.5 means the number of points are halved.
        - 0.25
      radius:               # In centimeters; Maximum radius to connect neighboring nodes. If set to None, it will be set to 1/sqrt(p) of the previous layer's radius. Typically, this results in the number of edges being reduced by ratio p.
        - 3.                # Base radius must not be None
      irreps_mlp_mid: 3     # irreps multiplier for mlp, like that of transformers.
      pool_method: 'fps'
      attn_type: 'mlp'
      alpha_drop: 0.1       
      proj_drop: 0.1
      drop_path_rate: 0.0
      n_layers_midstream: 2 # Number of layers that connects downstream to upstream

  query_model: 'StaticKeypointModel'
  query_kwargs:
    irreps_output: '64x0e+32x1e+16x2e'
    keypoint_coords:  # In centimeters
      - [0., -4.5, 10.]
      - [0., 4.5, 10.]
      # - [0., 0., 15.]

