device: 'cuda:0'

trainset:
  dataset_dir: 'demo/sapien_demo_5_bottle_20230729'
  annotation_file: 'data.yaml'
  n_batches: 1
  shuffle: True

testset:
  dataset_dir: 'demo/sapien_demo_5_bottle_20230729'
  annotation_file: 'data.yaml'
  n_batches: 1
  shuffle: False

model_config_file: 'score_model_configs.yaml'
log_root_dir: 'runs'

rescale_factor: &rescale_factor 100.0 # Meters to Centimeters
preprocess_config:
  - name: "crop_bbox"
    kwargs:
      targets: ['scene_pcd']
      bbox: [[-0.4, 0.4], [-0.8, 0.8], [0.5, 1.3]]  # In meters, [[x_min, x_max], [y_min, y_max], [z_min, z_max]]
  - name: "downsample"
    kwargs:
      voxel_size: 0.010  # In meters
      coord_reduction: "average"
  - name: "rescale"
    kwargs:
      rescale_factor: *rescale_factor


max_epochs: 200
n_epochs_per_checkpoint: 20
n_samples_x_ref: 10

diffusion_configs:
  t_augment: null
  time_schedules:
    - [0.1, 0.03]
    - [0.03, 0.003]


optimizer_kwargs:
  lr: 0.0003
  betas: [0.9, 0.98]
  eps: 0.000000001 # 1e-9
  weight_decay: 0.0001 # 1e-4
  amsgrad: True

