device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/panda_bowl/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_11_12_14-27-54_Pick_LowRes_Panda_Bowl/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/panda_bowl/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_11_12_15-16-35_Pick_HiRes_Panda_Bowl/checkpoint/200.pt'
      n_warmups: 10
  # pick_critic_kwargs:
  #   configs_root_dir: 'configs/panda_bowl/pick_ebm'
  #   train_configs_file: 'train_configs.yaml'
  #   task_configs_file: 'task_configs.yaml'
  #   checkpoint_dir: 'runs/2023_10_05_00-48-58_Pick_EBM_Panda/checkpoint/200.pt'
  #   n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/panda_bowl/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_11_12_16-22-45_Place_LowRes_Panda_Bowl/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/panda_bowl/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_11_12_17-20-22_Place_HiRes_Panda_Bowl/checkpoint/200.pt'
      n_warmups: 10
  place_critic_kwargs:
    configs_root_dir: 'configs/panda_bowl/place_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: 'runs/2023_11_12_19-44-46_Place_EBM_Panda_Bowl/checkpoint/200.pt'
    n_warmups: 10