pick_diffusion_configs:
  N_steps_list: [[250, 250], [250, 250]]
  timesteps_list: [[0.02, 0.02], [0.02, 0.02]]
  temperatures_list: [[1., 1.], [1., 1.]]
  diffusion_schedules_list:
    - null
    - null
  log_t_schedule: True
  time_exponent_temp: 1.0
  time_exponent_alpha: 0.5
pick_trajectory_configs:
  approach_len: 0.1
  n_steps: 10
place_diffusion_configs:
  N_steps_list: [[250, 250], [250, 250]]
  timesteps_list: [[0.02, 0.02], [0.02, 0.02]]
  temperatures_list: [[1., 1.], [1., 1.]]
  diffusion_schedules_list:
    - null
    - null
  log_t_schedule: True
  time_exponent_temp: 1.0
  time_exponent_alpha: 0.5
place_trajectory_configs:
  n_steps: 20
  dt: 0.0001
  cutoff_r: 0.05
  max_num_neighbors: 100
  eps: 0.0001
  cluster_method: 'knn'
  voxel_size: 0.01
  voxel_coord_reduction: 'average'



